server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /ivr-good/swagger-ui.html
    configUrl: /ivr-good/v3/api-docs/swagger-config
  api-docs:
    path: /v3/api-docs

openapi-info:
  url: https://pincode-dev.ru/ivr-good

telegram:
  bot:
    help_password: helpme
    search_password: searcherror
    username: ivr_stand_bot
    token:

flask-api:
  url: http://localhost:5004