server:
  port: 5003
  tomcat:
    max-http-form-post-size: 10485760
    max-swallow-size: -1

spring:
  datasource:
    url: jdbc:postgresql://dbivr:5432/postgres
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mail.ru
    port: 587
    username: min095@list.ru
    password: f4pBAwL8BEm7BWs1x1B1
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
  autoconfigure:
    exclude: io.awspring.cloud.autoconfigure.s3.S3AutoConfiguration
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
    configUrl: /ivr-good/v3/api-docs/swagger-config
    urls:
      - name: Default API
        url: /ivr-good/v3/api-docs
  api-docs:
    path: /v3/api-docs

openapi-requests:
  url: https://pincode-dev.ru/ivr-good

yandex:
  cloud:
    access:
    secret:
    bucket: akhidov-ivr

telegram:
  bot:
    help_password: helpme
    search_password: searcherror
    username: ivr_stand_bot
    token:

auth:
  reset-password:
    link: http://localhost:5003/users/update-password?userId=
  confirm-email:
    link: http://localhost:5003/users/confirm-email?userId=

flask-api:
  url: http://ivrgoodvector:5004