server:
  port: 5003

spring:
  datasource:
    url: jdbc:postgresql://dbivr:5432/postgres
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
    configUrl: /ivr-good/v3/api-docs/swagger-config
    urls:
      - name: Default API
        url: /ivr-good/v3/api-docs
  api-docs:
    path: /v3/api-docs

openapi-requests:
  url: https://pincode-dev.ru/ivr-good

telegram:
  bot:
    help_password: helpme
    search_password: searcherror
    username: ivr_stand_bot
    token:

flask-api:
  url: http://ivrgoodvector:5004
